### PR TITLE
Demo file and begining random

### PR DESCRIPTION
**Pull request by hazelduvall**
Hello again! Sorry about that; I was using an old version.

Besides the new demo file, I also would like to add support for a partial random module. It doesn't have to do everything, just provide basic random number functionality while not having to cut and paste code.

Thanks for allowing me to contribute!

### CODE REVIEW

**Comment by Vogtinator** [comment]
It doesn't make much sense to add a placeholder in the main repo IMO, I'll merge it when it's working.
Could you make a request just with ca152fc?

**Comment by Vogtinator** [comment]
BTW: You don't have to create a new pull request, it detects changes in your fork automatically.

**Comment by hazelduvall** [comment]
how would I create a pull request with one change? I'm new to github...

**Comment by Vogtinator** [comment]
Create a branch in your repo, then revert nspire to ca152fc and push.

**Comment by hazelduvall** [comment]
Sorry, how do I revert changes?

**Comment by Vogtinator** [comment]
The right way is to use git revert, but I like to invoke "git rebase -i HEAD^^^" and remove the commits.

**Comment by hazelduvall** [comment]
Alright, thanks for your patience! I'll have the pull request to you in a minute.

**Comment by hazelduvall** [comment]
There we go!

**Comment by Vogtinator** [comment]
You added some more revert commits, rebasing is now the only way to go.

**Pull request closed without merging**
